// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDockerStatus() {
  return window['go']['main']['App']['CheckDockerStatus']();
}

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function OpenDashboard() {
  return window['go']['main']['App']['OpenDashboard']();
}

export function OpenDockerDesktop() {
  return window['go']['main']['App']['OpenDockerDesktop']();
}

export function OpenInstallPage() {
  return window['go']['main']['App']['OpenInstallPage']();
}

export function OpenRazorpayDashboard() {
  return window['go']['main']['App']['OpenRazorpayDashboard']();
}

export function WriteEnvAndLaunch(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['WriteEnvAndLaunch'](arg1, arg2, arg3, arg4, arg5);
}
