// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckDockerStatus():Promise<main.DockerStatus>;

export function GetOS():Promise<string>;

export function OpenDashboard():Promise<void>;

export function OpenDockerDesktop():Promise<void>;

export function OpenInstallPage():Promise<void>;

export function OpenRazorpayDashboard():Promise<void>;

export function WriteEnvAndLaunch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.LaunchResult>;
